spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Derek-yzh/SpringCloud-Config-Center.git
          default-label: main
          search-paths: /**
  application:
    name: config

server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/